apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/shannon36/gc-sus-frontend:568cf8314cbc0cefc10ac313c16564ef5b0d725a
          name: frontend
          ports:
            - containerPort: 80
          resources: {}
      imagePullSecrets:
        - name: pullsecret