apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
        - port: 80
          image: ghcr.io/shannon36/gc-sus-frontend:bbc9b0ddd9e43d92e1ca7b917c8b2a948e99cb9f
          name: frontend
          resources: {}
      imagePullSecrets:
        - name: pullsecret
