apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: frontend
  name: frontend
  namespace: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: frontend
    spec:
      containers:
        - image: ghcr.io/shannon36/gc-sus-frontend:04c2509d159fc80d3bae61f94837c6d5c8da6146
          name: frontend
          ports:
            - containerPort: 80
          resources: {}
      securityContext:
        sysctls:
          - name: net.ipv4.ip_unprivileged_port_start
            value: "0"
      imagePullSecrets:
        - name: pullsecret
