apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    name: frontendservice
  name: frontendservice
  namespace: frontend
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
  selector:
    app: frontend
  #temporaily change from LoadBalancer to NodePort for dev purposes 
  type: NodePort
