apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    name: frontendservice
  name: frontendservice
  namespace: backend
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer
