apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontendapp
    name: frontendservice
  name: frontendservice
  namespace: frontend
spec:
  ports:
    - name: 8080-8080
      port: 80
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
  type: LoadBalancer
