apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontend
    name: frontend
  name: frontend
  namespace: frontend
spec:
  ports:
    - name: http
      port: 80
      protocol: TCP
    #  targetPort: 9377
    #- name: https
    #  port: 443
    #  protocol: TCP
    #  targetPort: 8080
  selector:
    app: frontend 
  type: LoadBalancer
