apiVersion: v1
kind: Service
metadata:
  labels:
    app: frontendapp
    name: frontendservice
  name: frontendservice
  namespace: frontend
spec:
  ports:
    - name: 80-80
      port: 80
      protocol: TCP
  selector:
    app: frontend
  type: LoadBalancer
