apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: allow-angular-springboot-access
  namespace: backend
spec:
  podSelector:
    matchLabels:
      app: backend
  #ingress traffic from frontend
  ingress:
  - from:
    - namespaceSelector:
        matchLabels:
          name: frontend
    ports:
    - protocol: TCP
      port: 8080
