apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: backend
  name: backend
  namespace: backend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: backend
    spec: 
      containers:
        - image: ghcr.io/shannon36/gc-sus-backend:863bf7f85616c149c9907373595e89c21f2cfeaa
          name: backend
          env:
          - name: DB_USER
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: db-user
          - name: DB_PASSWORD
            valueFrom:
              secretKeyRef:
                name: backend-secret
                key: db-password
          ports:
            - containerPort: 80
          resources: {}
      imagePullSecrets:
        - name: pullsecret