apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    name: backendservice
  name: backendservice
  namespace: backend
spec:
  ports:
    - name: 9090-9090
      port: 9090
      protocol: TCP
      targetPort: 9090
  selector:
    app: backend
  #change from ClusterIP to NodePort for dev purposes
  type: ClusterIP
