apiVersion: v1
kind: Service
metadata:
  labels:
    app: backendapp
    name: backendservice
  name: backendservice
  namespace: backend
spec:
  ports:
    - name: 8080-8080
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: frontend
  type: ClusterIP
