apiVersion: v1
kind: Service
metadata:
  labels:
    app: backend
    name: backend
  name: backend
  namespace: backend
spec:
  ports:
    - name: http 
      #change from 8080 to 80 to test out
      port: 80 
      protocol: TCP
    #  targetPort: 9376
    #- name: https
    #  port: 8443
    #  protocol: TCP 
    #  targetPort: 9090
  selector:
    app: backend
  #change from ClusterIP to LoadBalancer for dev purposes
  type: LoadBalancer
