apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb
    name: mariadb
  name: mariadb
  namespace: mariadb
spec:
  ports:
    - name: 3306-3306
      port: 3306
      protocol: TCP
  selector:
    app: mariadb
  type: LoadBalancer
